# Generated by Django 4.1.5 on 2023-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_time', models.DateField(auto_now=True)),
                ('post_image', models.ImageField(upload_to='event_images/')),
                ('post_text', models.TextField(max_length=300)),
            ],
        ),
    ]
